# CI 성공 후, 브랜치 푸시 시 staging/production 배포
name: CD

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
  push:
    branches: [develop, main]

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes \
            --environment=${{ github.ref_name == 'main' && 'production' || 'preview' }} \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          vercel deploy --prebuilt \
            ${{ github.ref_name == 'main' && '--prod' || '' }} \
            --token=${{ secrets.VERCEL_TOKEN }}
